"""Application state — loads artifacts once and wires the services together."""
from __future__ import annotations

import logging

from backend.config.loader import Settings, load_settings
from backend.models.loader import BottleneckBundle, DefectBundle, load_bottleneck, load_defect, load_metrics
from backend.services.bottleneck import BottleneckService
from backend.services.defect import DefectService
from backend.services.engine import TwinEngine
from backend.services.integration import IntegrationService
from backend.services.pnl import PnLEngine
from backend.services.simulator import LineSimulator
from backend.store.db import init_engine

log = logging.getLogger("cascade")


class AppState:
    settings: Settings
    bn: BottleneckBundle
    df: DefectBundle
    engine: TwinEngine
    metrics: dict

    def __init__(self) -> None:
        self.ready = False

    def boot(self) -> None:
        self.settings = load_settings()
        init_engine(self.settings)
        # Artifacts only — the backend never trains (Architecture §7).
        self.bn = load_bottleneck(self.settings)
        self.df = load_defect(self.settings)
        self.metrics = load_metrics(self.settings)

        bottleneck = BottleneckService(self.settings, self.bn)
        defect = DefectService(self.settings, self.df)
        integration = IntegrationService(self.settings, self.df.learned_chains)
        pnl = PnLEngine(self.settings)
        simulator = LineSimulator(self.settings, self.bn, self.df)

        self.engine = TwinEngine(self.settings, simulator, bottleneck, defect, integration, pnl)
        self.ready = True
        log.info("cascade ready: %d stations, defect layer %s",
                 self.bn.n_stations, "ON" if defect.enabled else "OFF (no detector artifact)")

    # ── provenance, built from live state (never a hardcoded UI string) ──
    def provenance(self) -> dict:
        m = self.metrics or {}
        bn_m = m.get("bottleneck", {})
        det_m = m.get("detector", {})
        ch_m = m.get("chains", {})
        real = [
            f"BSTAN bottleneck forecaster - test RMSE {bn_m.get('test_rmse', 'n/a')} "
            f"(beats persistence {bn_m.get('baseline_persistence_rmse', 'n/a')} and "
            f"moving-average {bn_m.get('baseline_moving_avg_rmse', 'n/a')}), "
            f"{100 * bn_m.get('localization_within_2_no_edge', 0):.0f}% localization within "
            f"+/-2 stations excluding edge stations, with confidence gating that abstains "
            f"instead of guessing.",
            f"Defect-chain engine - recovers {ch_m.get('recovered', 0)}/{ch_m.get('planted', 0)} "
            f"planted causal chains from {ch_m.get('history_vehicles', 0)} vehicle inspection "
            f"records.",
        ]
        if self.df.yolo_loaded:
            real.insert(0, (
                f"Fine-tuned YOLOv8 defect detector - mAP50 {det_m.get('mAP50', 'n/a')}, "
                f"precision {det_m.get('precision', 'n/a')}, recall {det_m.get('recall', 'n/a')}, "
                f"F1 {det_m.get('f1', 'n/a')} on {det_m.get('test_images', 'n/a')} real test "
                f"images, trained on {det_m.get('train_images', 'n/a')} real labelled images."))
        else:
            real.append(
                "Defect detector NOT LOADED in this instance - the visual layer is off and "
                "emits no detections. Its published metrics are not claimed here.")
        return {
            "real": real,
            "simulated": [
                "The vehicle line itself: 35-station layout, buffer sizes, per-shift process "
                f"features and inspection history, generated by a simulator "
                f"(seed {self.settings.line['simulator']['seed']}).",
                "vehicle_id, station_id and timestamp on defect events - the defect dataset has "
                "no automotive line context, so these are assigned by a config layer.",
            ],
            "assumed": [
                f"CAMERA_TO_STATION mapping ({len(self.settings.camera_to_station)} cameras) - "
                f"which camera sits at which station.",
                f"The visual->process defect mapping "
                f"({len(self.settings.visual_to_process)} rules) - a rule-based prototype "
                f"taxonomy a real plant's QA team would validate.",
                "All P&L cost assumptions - user-editable, never measured savings.",
            ],
            "statement": (
                "The mechanisms - detection, chaining, forecasting, gating - are real and "
                "validated. The factory around them is a realistic simulation, exactly as PS4 "
                "invites (a working proof-of-concept on illustrative data)."),
        }

    def models_status(self) -> dict:
        return {
            "bottleneck": {
                "loaded": True,
                "ensemble_size": len(self.bn.ensemble),
                "T_w": self.bn.T_w,
                "conf_threshold": self.bn.conf_threshold,
                "n_stations": self.bn.n_stations,
                "features": self.bn.features,
                "source": "exported artifacts (never retrained at runtime)",
            },
            "defect": self.engine.defect.status(),
            "chains": {
                "loaded": True,
                "rules": int(len(self.df.learned_chains)),
                "min_lift": self.settings.min_lift,
                "note": "separate layer from BSTAN; joins only at the twin-state record",
            },
        }


state = AppState()
